### ISSUE TITLE
Add Sentry Application Monitoring and Error Tracking Software

### ISSUE THREAD

**Issue by Phoqe** [Phoqe/react-material-ui-firebase#312]
- [x] Add base support for Sentry
- [x] Add release tracking
- [ ] Add setup step for Sentry in README.md
- [ ] Integrate Sentry release tracking in release process
